v1.5.1
 - fix: mount rpc_pipefs at bootup
 - fix: check rpc_pipefs in rpc.gssd, rpc.idmapd
 - fix: rpc.statd runscript
 - change: cleaner idmapd start/stop behavior
 - add: blkmapd runscript

diff --git a/etc/sv/rpc.idmapd/run b/etc/sv/rpc.idmapd/run
--- a/etc/sv/rpc.idmapd/run
+++ b/etc/sv/rpc.idmapd/run
@@ -1,6 +1,11 @@
 #!/bin/sh
 # NFSv4 kernel client and server ID <-> Name Mapper
+#
 # Activated automatically from rpcbind
+# NOTE: on more recent kernels only the NFSv4 server uses rpc.idmapd,
+# the client uses nfsidmap instead, and only falls back to rpc.idmapd
+# if there was a problem running the nfsidmap program.
+#
 # (cloux@rote.ch)
 exec 2>&1
 
@@ -8,4 +13,11 @@ DAEMON=$(command -v rpc.idmapd)
 [ -x "$DAEMON" ] || exit
 sv start rpcbind || exit
 
+# Ensure that the RPC pipefs is available
+if ! (mount | grep -q '^rpc_pipefs'); then
+	printf "ERROR: rpc.idmapd requires rpc_pipefs to be mounted.\n"
+	exit 1
+fi
+
+# Run daemon
 exec "$DAEMON" -f
