v1.6.7
 - fix: remove runscripts shell -e and -u parameters for higher reliability.
   This was causing e.g. hiawatha runscript to fail unnecessarily
 - fix: kernel-update.sh - update-grub requires /usr/sbin in PATH
 - add: mysql runscript - check data store availability
 - add: openvpn runscript - enable IPV4 masquerading on all interfaces

diff --git a/etc/sv/mysql/run b/etc/sv/mysql/run
--- a/etc/sv/mysql/run
+++ b/etc/sv/mysql/run
@@ -5,10 +5,20 @@ exec 2>&1
 DAEMON="$(command -v mysqld)"
 [ -x "$DAEMON" ] || exit
 
-export HOME=/etc/mysql/
 [ -f /etc/default/mysql ] && . /etc/default/mysql
 [ -f /etc/default/mariadb ] && . /etc/default/mariadb
-[ -r /etc/mysql/my.cnf ] || echo "WARNING: /etc/mysql/my.cnf cannot be read."
 [ -e /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld
+
+export HOME=/etc/mysql
+if [ ! -r "$HOME/my.cnf" ]; then
+	printf "ERROR: %s/my.cnf cannot be read." "$HOME"
+	exit 1
+fi
+
+DATADIR=$(grep '^datadir' "$HOME/my.cnf" | sed 's/.*=\s*//')
+if [ ! -d "$DATADIR" ]; then
+	printf "ERROR: datadir in %s/my.cnf is not a directory." "$HOME"
+	exit 1
+fi
 
 exec chpst -u mysql "$DAEMON"
